//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchFileLog
    {
        public int ID { get; set; }
        public string searchPattern { get; set; }
        public string searchPatternPath { get; set; }
        public string resultPatternPath { get; set; }
        public Nullable<System.DateTime> searchDate { get; set; }
    }
}
